### ISSUE TITLE
Saudi Arabia flag icon is incorrect

### ISSUE THREAD

**Issue by rishikesh-janrao** [catamphetamine/country-flag-icons#13]
![image](https://github.com/catamphetamine/country-flag-icons/assets/65944832/67610998-2f58-4b40-9596-b4512ad72309)

Correct one is below

![image](https://github.com/catamphetamine/country-flag-icons/assets/65944832/1e580e6f-21e1-4b0d-ad05-752c623fd70b)

**Comment by catamphetamine** [comment]
Nah, that's fine

**Comment by catamphetamine** [comment]
The original is too detailed and flag icons should be minimalistic, otherwise the SVG file size is big.

**Comment by rishikesh-janrao** [comment]
Firstly, I wonder if this was intentional, because a country flag is something critical for doing business in their countries and its also does not match the authenticity(because of the hebrew wordings).
Secondly, we can optimise size if needed but changing original content of a flag does not fit with size excuse.


Since multiple peoples are using this package shouldn't it be really for users?
I thought this package was truly open source. 
Thanks for contributing so far!

**Comment by catamphetamine** [comment]
> Firstly, I wonder if this was intentional.

Yes. 

> because a country flag is something critical for doing business in their countries and its also does not match the authenticity(because of the hebrew wordings).

That's actually funny if it indeed resembles Hebrew or whatnot 😆. 
Especially with the Gaza bombing controversy.

I don't know Hebrew so I can't tell. I'm also not a designer so I won't be re-drawing the characters into something else, and even if I did, it could turn out Hebrew again. So maybe some day a Saudi designer comes and re-draws the flag in a more proper fashion, but until then, it'll have to stay as is. 

I guess the original flag icon was copy-pasted from: https://flagpack.xyz/
And I didn't draw it.

> Secondly, we can optimise size if needed but changing original content of a flag does not fit with size excuse.

It does. If you don't like the flag being altered then you could use another collection of flags.

> I thought this package was truly open source.

It is open-source. There're no restrictions on copying, modifying, distributing the contents of the package. You could even create your own fork of it for your personal use.

------------------

So the summary is: if some arabic designer draws a flag of Saudi Arabia that is no larger than ~3 KB then we could replace it. Until then, the original flag is too big to be put in this library.

**Comment by Adam-Saeed** [comment]
Hi, I was actually searching for the source of the design. I hope this is it. I did make a modified version with a different way to it. Saudi Arabia does have another symbol, it's a palm tree with two swords. I hope this is within the requirements 
![sa modified](https://github.com/user-attachments/assets/bc3061d2-0261-4412-8d18-4e15d7678e23)

**Comment by Adam-Saeed** [comment]
![SA (2)](https://github.com/user-attachments/assets/ca65fd98-89e7-4d06-b1e5-e415ff7638fc)

**Comment by Adam-Saeed** [comment]
If this is considered too much creative liberty, then dropping the writing entirely and keeping just the sword is a viable option and did happen in multiple areas (like in Dying Light 1 game as they removed the text)

**Comment by catamphetamine** [comment]
@Adam-Saeed Hi. Interesting suggestion but I'd also consider it "too much creative liberty" because it doesn't even resemble the original Saudi Arabia flag:
https://ru.m.wikipedia.org/wiki/%D0%A4%D0%B0%D0%B9%D0%BB:Flag_of_Saudi_Arabia.svg

Leaving just a sword is also an interesting suggestion. It's just a matter of preference then. Aesthetically, I still think that having some letters (or quasi-letters) is better than not having any.

If the letters are not Saudi ones then it's fine (by my standards): it's not gibberish and it doesn't offend anyone. The quasi-letters themselves might look weird though, that I agree with. You could suggest your own variant: something to replace those letters with. It could be any set of any shapes that loosely resembles the original letters on the Saudi Arabia flag. Currently it looks like `JWIJ` which, I agree, doesn't make any sense either.

**Comment by rishikesh-janrao** [comment]
@catamphetamine  @Adam-Saeed,
I understand the efforts of maintaining this library, the point of opening this issue was not to just suggest change in design, but more of a business oriented concern about this library.
So I received a feedback from Saudi team about the impact of using incorrect flag on business(we unintentionally can enrage natives using this flag and you can get your business banned/boycotted as a result), and the fact that we are using wikipedia as source of truth is also not correct, most of the countries don't see wikipedia as authentic source of information.

As Mr. Nikolay said, we can either use this library or don't use it(after all country flag can be a personal preference as per this guy.. lol)

**Comment by catamphetamine** [comment]
> I understand the efforts of maintaining this library

I don't really maintain it anymore that much ☺️
Just merging in required fixes.

> So I received a feedback from Saudi team about the impact of using incorrect flag on business(we unintentionally can enrage natives using this flag and you can get your business banned/boycotted as a result)

That's true.

> and the fact that we are using wikipedia as source of truth is also not correct, most of the countries don't see wikipedia as authentic source of information.

Actually, they do, in the Western world.

> As Mr. Nikolay said, we can either use this library or don't use it

Also, it could be used partially: some flags could be selectively replaced by creating a custom wrapper around this library.
One could even create a personal fork with just one flag being replaced.

The current status of this library is: I'm not really interested in all this stuff anymore. If a country adopts a new flag, we change it. But it would have to match the actual flag almost 1:1. With Saudi Arabia, a 1:1 match is not possible, so it has to be something improvised. When a person looks at a small "icon" of a flag, the small details are indistinguishable so the "personal preference" letters would have to be an approximation of the official ones as seen on the official flag. The current variant works for me personally because I don't speak arabic so I don't have a slightest idea if those're real letters or just a funny drawing.
